package com.example.util

enum class AppLanguage {
    TR, EN
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        val mapTR = mapOf(
            "app_name" to "EduPLAN",
            "agenda_title" to "Ödev Ajandası",
            "calendar_title" to "Takvim",
            "past_homeworks" to "Geçmiş Ödevler",
            "completed_homeworks" to "Tamamlananlar",
            "expired_homeworks" to "Süresi Geçenler",
            "settings" to "Ayarlar",
            "add_homework" to "Yeni Ödev Ekle",
            "edit_homework" to "Ödevi Düzenle",
            "date" to "Tarih",
            "subject" to "Ders",
            "select_subject" to "Ders Seçin",
            "custom_subject" to "+ Özel Ders Ekle",
            "custom_subject_title" to "Yeni Ders Ekle",
            "subject_name_placeholder" to "Ders Adı (örn. İspanyolca)",
            "difficulty" to "Zorluk Derecesi",
            "easy" to "Kolay",
            "normal" to "Normal",
            "hard" to "Zor",
            "is_project" to "Proje Ödevi mi?",
            "yes" to "Evet",
            "no" to "Hayır",
            "project_badge" to "PROJE ÖDEVİ",
            "notes" to "Ödev Notu / Açıklama",
            "notes_placeholder" to "Örn. Sayfa 45-50 alıştırmalar...",
            "save" to "Kaydet",
            "cancel" to "İptal",
            "delete" to "Sil",
            "confirm_delete" to "Bu ödevi silmek istediğinizden emin misiniz?",
            "mark_completed" to "Tamamlandı olarak işaretle",
            "mark_pending" to "Bekliyor olarak değiştir",
            "theme" to "Tema Seçimi",
            "theme_light" to "Açık Tema",
            "theme_dark" to "Koyu Tema",
            "theme_system" to "Sistem Teması",
            "language" to "Dil Seçimi",
            "lang_tr" to "Türkçe",
            "lang_en" to "English",
            "qr_share_title" to "QR Kod ile Ajanda Paylaşımı",
            "qr_share_button" to "Ajandayı Paylaş (QR Kod)",
            "qr_import_button" to "QR Kod ile İçe Aktar",
            "qr_share_desc" to "Mevcut ödevlerinizi içeren QR koda dönüştürür. Başka bir cihazdan tarayarak aktarabilirsiniz.",
            "qr_import_desc" to "Taranan veya yapıştırılan QR kod verisini EduPLAN ajandanıza aktarır.",
            "paste_qr_data" to "QR Verisini / JSON Yapıştırın",
            "import" to "İçe Aktar",
            "qr_imported_success" to "ödev başarıyla ajandanıza aktarıldı!",
            "today_homeworks" to "Bugünün Ödevleri",
            "upcoming_homeworks" to "Yaklaşan Ödevler",
            "no_homeworks_day" to "Bu tarih için kayıtlı ödev bulunmuyor.",
            "no_active_homeworks" to "Harika! Aktif bekleyen ödeviniz yok.",
            "stats_title" to "Haftalık Özet & İstatistik",
            "completed_this_week" to "Bu Hafta Tamamlanan",
            "pending_total" to "Bekleyen Ödevler",
            "filter_subject" to "Derse Göre Filtrele",
            "filter_difficulty" to "Zorluğa Göre Filtrele",
            "all_subjects" to "Tüm Dersler",
            "all_difficulties" to "Tüm Zorluklar",
            "notifications_title" to "Otomatik Bildirim Sistemi",
            "notification_info" to "• Kolay/Normal ödevler: 1 gün önce 18:00 ve 20:00\n• Zor ödevler: 2 gün önce 18:00 ve 20:00\n• Proje ödevleri: +3 gün önce 15:25 malzeme hatırlatması",
            "material_reminder_title" to "Malzeme Hazırlatma",
            "custom_subjects_title" to "Özel Ders Listeniz",
            "no_custom_subjects" to "Henüz özel ders eklenmedi.",
            "share_app" to "Uygulamayı Paylaş",
            "days_left" to "gün kaldı",
            "due_today" to "BUGÜN SON GÜN",
            "expired_badge" to "SÜRESİ GEÇTİ",

            // Newly Added Localization Strings
            "ok" to "Tamam",
            "yes_delete" to "Evet, Sil",
            "no_keep" to "Hayır",
            "close" to "Kapat",
            "copy" to "Kopyala",
            "copied" to "Kopyalandı!",
            "delete_record_title" to "Kayıt Dosyasını Sil",
            "delete_record_confirm" to "ses kaydı dosyasını silmek istediğinize emin misiniz?",
            "pro_recordings_title" to "Pro Mod Kayıtları (.md)",
            "pro_recordings_count" to "adet oturum dosyası",
            "pro_recordings_empty" to "Henüz kaydedilmiş Pro Mod ses kaydı (.md) bulunmuyor.\n'Pro Kayıt Başlat' butonu ile yeni bir sesli transkript oluşturabilirsiniz.",
            "pro_mode_title" to "Pro Mod • Ses Kaydı & Transkripsiyon",
            "pro_mode_desc" to "Pro Mod açıkken 'Pro Kayıt Başlat' butonu aktifleşir. Butona basıldığı an tüm konuşmalar gerçek zamanlı olarak tarih damgalı .md dosyasına yazılır.",
            "start_pro_recording" to "Pro Kayıt Başlat",
            "stop_pro_recording" to "Kaydı Durdur",
            "recordings_btn" to "Kayıtlar",
            "privacy_battery_note" to "🔒 Pil & Gizlilik: Kayıt aktif değilken mikrofon tamamen kapalıdır. Transkripsiyon %100 Cihaz Üzerinde (On-Device) işlenir.",
            "auto_notification_title" to "Otomatik Bildirim Sistemi",
            "auto_notification_sub" to "Ödev hatırlatmalarını düzenleyin",
            "first_reminder" to "1. Hatırlatma",
            "second_reminder" to "2. Hatırlatma",
            "project_notification" to "Proje Bildirimi",
            "hard_hw_notification" to "Zor Ödev Bildirimi",
            "days_before" to "Gün Önce",
            "reset_notification_defaults" to "Varsayılan Moda Dön",
            "voice_hw_detected" to "Pro Mod • Sesli Ödev Algılandı",
            "voice_hw_check_prompt" to "Lütfen oluşturulan ödev bilgilerini kontrol edin ve onaylayın:",
            "confirm_and_save" to "Onayla & Kaydet",
            "qr_share_prompt" to "Ajandanızdaki ödevleri QR kod olarak başkalarıyla paylaşabilir veya var olan QR koddan ödev yükleyebilirsiniz.",
            "qr_empty_message" to "Ajandanızda paylaşılacak ödev bulunamadı.",
            "qr_sharing_count" to "adet ödev paylaşılıyor",
            "qr_multi_series" to "Çoklu QR Serisi: Parça",
            "qr_prev" to "← Önceki QR",
            "qr_next" to "Sonraki QR →",
            "share_action" to "Paylaş",
            "save_gallery" to "Galeriye Kaydet",
            "saved_action" to "Kaydedildi",
            "copy_qr_text" to "QR Metnini Kopyala",
            "camera_tab" to "Kamera",
            "gallery_tab" to "Galeri",
            "text_tab" to "Metin",
            "rescan" to "Yeniden Tara",
            "import_to_agenda" to "Ajandaya Aktar",
            "camera_no_perm" to "Kamera izni verilmedi. Ayarlardan izin verebilir veya Galeriden / Metinden Yükle seçeneğini kullanabilirsiniz.",
            "load_from_gallery_text" to "Galeriden / Metinden Yükle",
            "align_qr_center" to "QR kodu çerçevenin ortasına hizalayın",
            "gallery_select_prompt" to "Galerinizden önceden kaydedilmiş bir EduPLAN QR kod görseli seçin.",
            "select_qr_gallery_btn" to "Galeriden QR Görseli Seç",
            "qr_text_content_label" to "QR Kod Metin İçeriği",
            "qr_text_placeholder" to "EduPLAN QR JSON verisini buraya yapıştırın...",
            "paste_from_clipboard" to "Panodan Yapıştır",
            "decode_and_preview" to "Çözümle & Önizle",
            "duplicate_hw_title" to "Aynı Ödevler Algılandı",
            "duplicate_hw_prompt" to "Ajandanızda aynı ders ve tarihe sahip ödev bulundu. Yine de eklensin mi?",
            "add_all" to "Tümünü Ekle",
            "skip_duplicates" to "Kopyaları Atla",
            "pro_mode_warning_title" to "Pro Mod & Pil İzinleri Uyarı",
            "pro_mode_warning_body" to "Pro Mod açıldığında cihazınız 8 saat boyunca kesintisiz dinleme yapabilir ve konuşmaları zaman damgasıyla .md dosyasına kaydeder.\n\n🔑 İzinler: Sadece Pro Mod aktifleştirildiğinde Mikrofon ve Bildirim izinleri istenir.\n🔋 Pil Optimizasyonu: Arka planda 8 saat kesintisiz çalışması için pil optimizasyonu muafiyeti önerilir.\n\n🔒 Gizlilik Notu: Bütün ses işleme %100 Cihaz Üzerinde (On-Device) gerçekleştirilir ve ses verileriniz asla dışarıya gönderilmez.",
            "understand_activate" to "Anladım & Etkinleştir",
            "skip_for_now" to "Şimdilik Atla",
            "battery_opt_title" to "Arka Plan Pil Optimizasyonu",
            "battery_opt_body" to "8 saatlik kesintisiz dinleme ve ekran kapalıyken transkripsiyonun Android tarafından sonlandırılmaması için EduPLAN uygulamasını pil optimizasyonundan muaf tutmanız önerilir.",
            "go_to_settings_exempt" to "Ayarlara Git & Muaf Tut",
            "delete_subject_title" to "Dersi Sil",
            "delete_subject_confirm" to "özel dersini silmek istediğinize emin misiniz?",
            "detailed_view_title" to "Detaylı Ödev Görünümü",
            "tap_to_close" to "Dokun: Kapat ✕",
            "status" to "Durum:",
            "completed_status" to "✓ Tamamlandı",
            "expired_status" to "⚠️ Süresi Doldu",
            "active_hw_status" to "⏳ Aktif Ödev",
            "diff_type" to "Zorluk / Tür:",
            "project_suffix" to " • Proje Ödevi",
            "created_at" to "Oluşturulma:",
            "no_extra_notes" to "Bu ödev için ek not bulunmuyor.",
            "edit_hint" to "✏️ Düzenlemek için sağ üstteki kalem butonuna basabilirsiniz.",
            "delete_homework_title" to "Ödevi Sil",
            "homeworks_suffix" to "Ödevleri",
            "pro_listening" to "PRO DİNLENİYOR"
        )

        val mapEN = mapOf(
            "app_name" to "EduPLAN",
            "agenda_title" to "Homework Planner",
            "calendar_title" to "Calendar",
            "past_homeworks" to "Past Homeworks",
            "completed_homeworks" to "Completed",
            "expired_homeworks" to "Expired",
            "settings" to "Settings",
            "add_homework" to "Add New Homework",
            "edit_homework" to "Edit Homework",
            "date" to "Date",
            "subject" to "Subject",
            "select_subject" to "Select Subject",
            "custom_subject" to "+ Add Custom Subject",
            "custom_subject_title" to "Add Custom Subject",
            "subject_name_placeholder" to "Subject Name (e.g. Spanish)",
            "difficulty" to "Difficulty Level",
            "easy" to "Easy",
            "normal" to "Normal",
            "hard" to "Hard",
            "is_project" to "Is Project Homework?",
            "yes" to "Yes",
            "no" to "No",
            "project_badge" to "PROJECT",
            "notes" to "Notes / Description",
            "notes_placeholder" to "E.g. Pages 45-50 exercises...",
            "save" to "Save",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "confirm_delete" to "Are you sure you want to delete this homework?",
            "mark_completed" to "Mark as Completed",
            "mark_pending" to "Mark as Pending",
            "theme" to "Theme",
            "theme_light" to "Light Theme",
            "theme_dark" to "Dark Theme",
            "theme_system" to "System Theme",
            "language" to "Language",
            "lang_tr" to "Türkçe",
            "lang_en" to "English",
            "qr_share_title" to "QR Code Agenda Sharing",
            "qr_share_button" to "Share Agenda (QR Code)",
            "qr_import_button" to "Import via QR Code",
            "qr_share_desc" to "Encodes your current homeworks into a QR code for easy transfer to another device.",
            "qr_import_desc" to "Imports scanned or pasted QR payload data into your EduPLAN agenda.",
            "paste_qr_data" to "Paste QR Code / JSON Data",
            "import" to "Import",
            "qr_imported_success" to "homeworks successfully imported to agenda!",
            "today_homeworks" to "Today's Homeworks",
            "upcoming_homeworks" to "Upcoming Homeworks",
            "no_homeworks_day" to "No homework registered for this date.",
            "no_active_homeworks" to "Awesome! You have no pending homeworks.",
            "stats_title" to "Weekly Summary & Stats",
            "completed_this_week" to "Completed This Week",
            "pending_total" to "Pending Homeworks",
            "filter_subject" to "Filter by Subject",
            "filter_difficulty" to "Filter by Difficulty",
            "all_subjects" to "All Subjects",
            "all_difficulties" to "All Difficulties",
            "notifications_title" to "Automatic Notification System",
            "notification_info" to "• Easy/Normal: 1 day before at 18:00 & 20:00\n• Hard: 2 days before at 18:00 & 20:00\n• Project: +3 days before at 15:25 material reminder",
            "material_reminder_title" to "Material Reminder",
            "custom_subjects_title" to "Your Custom Subjects",
            "no_custom_subjects" to "No custom subjects added yet.",
            "share_app" to "Share App",
            "days_left" to "days left",
            "due_today" to "DUE TODAY",
            "expired_badge" to "EXPIRED",

            // Newly Added Localization Strings
            "ok" to "OK",
            "yes_delete" to "Yes, Delete",
            "no_keep" to "No",
            "close" to "Close",
            "copy" to "Copy",
            "copied" to "Copied!",
            "delete_record_title" to "Delete Recording File",
            "delete_record_confirm" to "recording file? Are you sure you want to delete it?",
            "pro_recordings_title" to "Pro Mode Recordings (.md)",
            "pro_recordings_count" to "session files",
            "pro_recordings_empty" to "No Pro Mode voice recording (.md) found yet.\nYou can create a new transcript with the 'Start Pro Recording' button.",
            "pro_mode_title" to "Pro Mode • Voice Recording & Transcription",
            "pro_mode_desc" to "When Pro Mode is active, 'Start Pro Recording' button is enabled. When pressed, all speech is transcribed in real-time with timestamps into a .md file.",
            "start_pro_recording" to "Start Pro Recording",
            "stop_pro_recording" to "Stop Recording",
            "recordings_btn" to "Recordings",
            "privacy_battery_note" to "🔒 Battery & Privacy: Microphone is completely off when not recording. Transcription is processed 100% On-Device.",
            "auto_notification_title" to "Automatic Notification System",
            "auto_notification_sub" to "Customize homework reminders",
            "first_reminder" to "1st Reminder",
            "second_reminder" to "2nd Reminder",
            "project_notification" to "Project Notification",
            "hard_hw_notification" to "Hard Homework Notification",
            "days_before" to "Days Before",
            "reset_notification_defaults" to "Reset to Defaults",
            "voice_hw_detected" to "Pro Mode • Voice Homework Detected",
            "voice_hw_check_prompt" to "Please check and confirm the generated homework details:",
            "confirm_and_save" to "Confirm & Save",
            "qr_share_prompt" to "You can share homeworks in your agenda as a QR code or import homeworks from an existing QR code.",
            "qr_empty_message" to "No homework found in your agenda to share.",
            "qr_sharing_count" to "homeworks being shared",
            "qr_multi_series" to "Multi-QR Series: Part",
            "qr_prev" to "← Previous QR",
            "qr_next" to "Next QR →",
            "share_action" to "Share",
            "save_gallery" to "Save to Gallery",
            "saved_action" to "Saved",
            "copy_qr_text" to "Copy QR Text",
            "camera_tab" to "Camera",
            "gallery_tab" to "Gallery",
            "text_tab" to "Text",
            "rescan" to "Rescan",
            "import_to_agenda" to "Import to Agenda",
            "camera_no_perm" to "Camera permission not granted. You can grant permission in Settings or use Gallery / Text Import.",
            "load_from_gallery_text" to "Load from Gallery / Text",
            "align_qr_center" to "Align QR code in the center of the frame",
            "gallery_select_prompt" to "Select a previously saved EduPLAN QR code image from your gallery.",
            "select_qr_gallery_btn" to "Select QR Image from Gallery",
            "qr_text_content_label" to "QR Code Text Content",
            "qr_text_placeholder" to "Paste EduPLAN QR JSON data here...",
            "paste_from_clipboard" to "Paste from Clipboard",
            "decode_and_preview" to "Decode & Preview",
            "duplicate_hw_title" to "Duplicate Homeworks Detected",
            "duplicate_hw_prompt" to "Found homeworks with the same subject and date in your agenda. Add anyway?",
            "add_all" to "Add All",
            "skip_duplicates" to "Skip Duplicates",
            "pro_mode_warning_title" to "Pro Mode & Battery Permissions Warning",
            "pro_mode_warning_body" to "When Pro Mode is enabled, your device can continuously listen for 8 hours and record speech with timestamps into a .md file.\n\n🔑 Permissions: Microphone and Notification permissions are requested only when Pro Mode is enabled.\n🔋 Battery Optimization: Battery optimization exemption is recommended for 8 hours continuous background operation.\n\n🔒 Privacy Note: All audio processing is conducted 100% On-Device and audio data is never sent outside.",
            "understand_activate" to "Understand & Activate",
            "skip_for_now" to "Skip for Now",
            "battery_opt_title" to "Background Battery Optimization",
            "battery_opt_body" to "To prevent Android from terminating 8-hour continuous listening and transcription while the screen is off, it is recommended to exempt EduPLAN from battery optimization.",
            "go_to_settings_exempt" to "Go to Settings & Exempt",
            "delete_subject_title" to "Delete Subject",
            "delete_subject_confirm" to "custom subject? Are you sure you want to delete it?",
            "detailed_view_title" to "Detailed Homework View",
            "tap_to_close" to "Tap: Close ✕",
            "status" to "Status:",
            "completed_status" to "✓ Completed",
            "expired_status" to "⚠️ Expired",
            "active_hw_status" to "⏳ Active Homework",
            "diff_type" to "Difficulty / Type:",
            "project_suffix" to " • Project Homework",
            "created_at" to "Created At:",
            "no_extra_notes" to "No extra notes for this homework.",
            "edit_hint" to "✏️ You can press the pencil icon at top right to edit.",
            "delete_homework_title" to "Delete Homework",
            "homeworks_suffix" to "Homeworks",
            "pro_listening" to "PRO LISTENING"
        )

        return if (lang == AppLanguage.TR) mapTR[key] ?: key else mapEN[key] ?: key
    }
}
